baseURL: https://www.outcoldman.com
title: outcoldman
languageCode: en-us

enableRobotsTXT: true
disableKinds: ["taxonomy", "term"]
enableGitInfo: true

permalinks:
  en: /en/archive/:year/:month/:day/:slug/
  ru: /ru/archive/:year/:month/:day/:slug/
  cheatsheets: /cheatsheets/:filename/