stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - shell
  script:
    - make docker-bower-build
    - make docker-jekyll-build

deploy:
  stage: deploy
  tags:
    - shell
  script:
    - make docker-aws-deploy
