stages:
  - build
  - clean

build:
  stage: build
  tags:
    - shell
  except:
    - master
  script:
    - make docker-jekyll-build

build_and_deploy:
  stage: build
  tags:
    - shell
  only:
    - master
  script:
    - make docker-jekyll-build
    - make docker-aws-deploy

clean:
  stage: clean
  tags:
    - shell
  when: always
  script:
    - make docker-clean
