stages:
  - build
  - deploy
  - clean

build:
  stage: build
  tags:
    - shell
  script:
    - make docker-jekyll-build

deploy:
  stage: deploy
  tags:
    - shell
  only:
    - master
  script:
    - make docker-aws-deploy

clean:
  stage: clean
  tags:
    - shell
  when: always
  script:
    - make docker-clean

cache:
  untracked: true
  paths:
    - _site/
