#
# Blog Settings
#
author: Denis Gladkikh
description: Blog about software development
url: https://www.outcoldman.com
title: outcoldman

#
# Jekyll Settings
#
permalink: /:categories/archive/:year/:month/:day/:title/
timezone: Etc/UTC
encoding: utf-8

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

exclude:
  - .gitignore
  - Makefile
  - _config.yml
  - _local_config.yml
