#
# Blog Settings
#
author: Denis Gladkikh
description: Blog about software development
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.outcoldman.com
title: outcoldman
deployment: production

#
# Jekyll Settings
#
permalink: /:categories/archive/:year/:month/:day/:title/
safe: false

# Google Analytics
google_analytics_tracking_id: UA-7023371-5

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

exclude:
  - .gitignore
  - Dockerfile
  - Makefile
  - _config.yml
  - _local_config.yml
