#
# Blog Settings
#
author: Denis Gladkikh
description: Blog about software development
url: http://outcoldman.com
title: Blog about software development
deployment: production

#
# Jekyll Settings
#
markdown: redcarpet
permalink: /:categories/archive/:year/:month/:day/:title/
safe: false

# Disqus Comments
disqus_short_name: outcoldman
disqus_show_comment_count: false
disqus_registered_url: http://outcoldman.com

# Google Analytics
google_analytics_tracking_id: UA-7023371-5

gems:
  - jekyll-sitemap

exclude:
  - .gitignore
  - .ruby-version
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Makefile
  - _config.yml
  - _local_config.yml
  - _staging_config.yml
  - bower.json
  - bower_components
  - docker-compose.yml
  - node_modules
