url: http://localhost:4000
show_drafts: true
exclude:
  - _posts/ru/2008
  - _posts/ru/2009
  - _posts/ru/2010
  - _posts/ru/2011
  - _posts/ru/2012
  - _posts/ru/2013
  - _posts/en/2008
  - _posts/en/2009
  - _posts/en/2010
  - _posts/en/2011
  - _posts/en/2012
  - _posts/en/2013
  - _posts/en/2014
  - _posts/en/2015
  - _posts/en/2016
